### ISSUE TITLE
Support the between operator

### ISSUE THREAD

**Issue by lothar7** [NeilMacMullen/kusto-loco#2]
Might have overlooked something but I can't see any support for the between operator. Its rather nice when querying for a specific time ranges.

Like this
```
SomeData
| where StartTime between (datetime(2023-12-01T01:30:00) .. datetime(2023-12-01T08:00:00))
| count
```

**Comment by NeilMacMullen** [comment]
Alas there are a number of missing operators.  I've added a couple (case, getschema) and plan on adding more as time allows.  It's not too difficult to do - just a bit tedious.  Will write up some instructions for doing so at another time.

**Comment by NeilMacMullen** [comment]
implemented...   
![image](https://github.com/NeilMacMullen/kusto-loco/assets/9131337/52467e56-481f-4f2e-b384-4ae31ae9c3f7)
