### ISSUE TITLE
Support user defined function in c#

### ISSUE THREAD

**Issue by lothar7** [NeilMacMullen/kusto-loco#3]
It would be nice to be able to add a user defined function that is specified in c# code.

**Comment by NeilMacMullen** [comment]
This is already supported :-) see [this doc](https://github.com/NeilMacMullen/kusto-loco/blob/main/docs/additionalFunctions.md)
I've written a very [quick guide](https://github.com/NeilMacMullen/kusto-loco/blob/main/docs/addUserDefinedFunction.md).

If you'd like to add anything you are very welcome  :-)

**Comment by lothar7** [comment]
My apologies. Should have checked better. Thank you!

**Comment by NeilMacMullen** [comment]
Agreed - it shouldn't be necessary to have to touch the core engine code to add a new function- the longer term intention is to separate this in a way that allows run-time registration.  I'd also like to reduce the amount of required boilerplate code - InvokeScalar is usually just a degenerate case of InvokeColumnar and a base class could be provided to implement this as a default.

**Comment by devsbazefield** [comment]
Can't we just initially make "CustomFunctions.functions" public instead of internal so we can access it from outside the BabyCusto.Core project?
