### ISSUE TITLE
Support generating nuget packages from the kusto libraries

### ISSUE THREAD

**Issue by lothar7** [NeilMacMullen/kusto-loco#8]
It would be good to add  `<GeneratePackageOnBuild>true</GeneratePackageOnBuild>` to the source projects so we can generate nuget packages which can then be imported elsewhere.

**Comment by NeilMacMullen** [comment]
relevant info so I don't lose it....  https://markheath.net/post/multiple-nuget-single-repo

**Comment by NeilMacMullen** [comment]
This is now (finally!) done.  Search nuget for 'KustoLoco'
